### services###
apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: djnago
spec:
  ports:
    - port: 8000
  selector:
    app: django
    tier: app
  type: LoadBalancer


  ### volume ###
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-pvc
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


### app ###
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: app
    spec:
      volumes:
        - name: django--app-data
          persistentVolumeClaim:
            claimName: django-app-pvc
      containers:
        - image: django-proxy:latest
          imagePullPolicy: Never
          name: app
          # ports:
          #   - containerPort: 5432
          #     name: postgres
          volumeMounts:
            - name: django--app-data
              mountPath: /vol/web
          env:
            - name: DB_HOST
              value: django_postgres
            - name: DB_NAME
              value: djangodb
            - name: DB_USER
              value: djangodb
            - name: ALLOWED_HOST
              value: '127.0.0.1,localhost'
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-passward
                  key: passward
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django
                  key: secret
        - image: django-proxy:latest
          imagePullPolicy: Never
          name: app
          ports:
            - containerPort: 8000
              name: proxy
          volumeMounts:
            - name: django--app-data
              mountPath: /vol/web
          env:
            - name: APP_HOST
              value: '127.0.0.1'
            - name: APP_PORT
              value: '8080'
              